title: La Naturaleza del Software
baseurl: 'https://lnds.net/'
copyright: '&copy; Eduardo Díaz Cortés'
enableGitInfo: false
enableRobotsTXT: true
ignoreErrors:
  - error-output-taxonomy
rssLimit: 20
defaultContentLanguage: es
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
paginate: 10
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
blackfriday:
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true
  extensions:
    - backslashLineBreak
  unsafe: true
markup:
  goldmark:
    renderer:
      unsafe: true
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
permalinks:
  post: '/blog/lnds/:year/:month/:day/:slug'

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_