# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

# SEO
marketing:
  seo:
  analytics:
    google_analytics: ""
    google_tag_manager: ""
    google_site_verification: ""
    baidu_site_verification: ""
    baidu_tongji: ""

site_type: Person
local_business_type: ""
org_name: ""
description: ""
twitter: ""

# Contact (edit or remove options as required)

email: ""
phone: ""
contact_links:
  - icon: twitter
    icon_pack: fab
    name: DM Me
    link: "https://twitter.com/lnds"

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization
locale:
  date_format: "2006-01-02"
  time_format: "15:04"
  list_delimiter: ", "

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - rust
      - perl
      - ocaml
      - go
      - python
      - clojure
      - java
      - scala
      - c
      - julia
      - swift
      - kotlin
      - haskell
      - fsharp
      - erlang
  math:
    enable: false
  diagram:
    enable: false
  privacy_pack:
    enable: false
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: "disqus"
    disqus:
      shortname: lnds
      show_count: true
    commento:
      url: ""
  search:
    provider: wowchemy
    algolia:
      app_id: ""
      api_key: ""
      index_name: ""
      show_logo: false
  map:
    provider: ""
    api_key: ""
    zoom: 15

extensions:
  cms:
    branch: master
    local_backend: false
  academicons:
    enable: true
